'''
logo.py: Embedded icon for use in the "About" panel

The rest of this file was generated by using the img2py.py program that
is provided with wxPython 4.0, with the following commands:

  inkscape -z -e checkit-icon.png  -w 160  ../.graphics/checkit-icon.svg
  img2py -f -i -n Logo checkit-icon.png logo.py
  rm checkit-icon.png

The only changes to the output were to add the file header and this
explanatory comment.

Authors
-------

Michael Hucka <mhucka@caltech.edu> -- Caltech Library

Copyright
---------

Copyright (c) 2019 by the California Institute of Technology.  This code is
open-source software released under a 3-clause BSD license.  Please see the
file "LICENSE" for more information.
'''

#----------------------------------------------------------------------
# This file was generated by /Users/mhucka/system/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Logo = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAKAAAADICAYAAABvaOoaAAAABHNCSVQICAgIfAhkiAAAAAlw'
    b'SFlzAABibQAAYm0B2SZdSAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA'
    b'AAJ2SURBVHic7d3RSRxRFIDhO2IbLikj9qF2EQNJHQlk04XahykjrH3s5CGvMxt2EH403/e6'
    b'nHPvDL8+LIhjAAAAAAAAAAC8omnL0Hx/9WWM6Xpx4f5wuzjz6cPHMR2/Li+8+Db9/P1r+azd'
    b'4/kX3LJvfp72L9+XZ9af98QlNu17j+/vlMtzB/6arscYN2eNXByvxrwyc3F8GGMsPvDZ52ze'
    b'd+pnccPzvva+N/3+Thy1aQpeiQBJCZCUAEkJkJQASQmQlABJCZCUAEkJkJQASQmQlABJCZCU'
    b'AEkJkJQASQmQlABJCZCUAEkJkJQASQmQlABJCZCUAEkJkJQASQmQlABJCZCUAEkJkJQASQmQ'
    b'lABJCZCUAEkJkJQASQmQlABJCZCUAEkJkJQASQmQlABJCZCUAEkJkJQASQmQlABJCZCUAEkJ'
    b'kJQASQmQlABJCZCUAEkJkNQ03+/m+hL8v/wGJCVAUgIkJUBSAiQlQFICJCVAUgIkJUBSAiQl'
    b'QFKXYxp39SUAAAAA3r9py9B8v3scY9wsLtwfFnfOn3e3Yx4PK7e4m34cHlfOOv9vVrbte5r2'
    b'h9uVmdXnPWHTvvf4/k7xRTQpAZISICkBkhIgKQGSEiApAZISICkBkhIgKQGSEiApAZISICkB'
    b'khIgKQGSEiApAZISICkBkhIgKQGSEiApAZISICkBkhIgKQGSEiApAZISICkBkhIgKQGSEiAp'
    b'AZISICkBkhIgKQGSEiApAZISIKnLbWPz89n/aPN48TKm49PqZ+uWZ/511tn75uf1kQ3P+9r7'
    b'3vT7AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3o0/2cSSieFkB94AAAAASUVO'
    b'RK5CYII=')
getLogoData = Logo.GetData
getLogoImage = Logo.GetImage
getLogoBitmap = Logo.GetBitmap
getLogoIcon = Logo.GetIcon
